FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    python3-pip \
    gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server /app/server
COPY functional /app/functional
COPY performance /app/performance

WORKDIR /app

CMD ["robot", "-d", "results", "functional", "performance"]