name: Docker Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.test
        push: true
        tags: george1983/testrep:${{ github.sha }}

    - name: Run Robot Framework tests
      run: |
        docker pull george1983/testrep:${{ github.sha }}
        docker run --name robot_tests george1983/testrep:${{ github.sha }} /bin/sh -c "robot -d results functional/functional_tests.robot && robot -d results performance/performance.robot"
        docker cp robot_tests:/app/results/ .
        docker rm -f robot_tests

    - name: Upload Robot test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-test-results
        path: results
